"""
Comparison script to show Plotly Table vs Matplotlib table rendering
"""
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from io import BytesIO

# Sample data
sample_schedule = [
    {"week": 1, "date": "Jan 15, 2025 00:00", "track": "Daytona International Speedway - Road Course"},
    {"week": 2, "date": "Jan 22, 2025 00:00", "track": "Sebring International Raceway"},
    {"week": 3, "date": "Jan 29, 2025 00:00", "track": "Road Atlanta - Full Course"},
    {"week": 4, "date": "Feb 05, 2025 00:00", "track": "Watkins Glen International - Boot"},
    {"week": 5, "date": "Feb 12, 2025 00:00", "track": "Circuit of the Americas - Grand Prix"},
]

COLORS = {
    'bg_dark': '#0f172a',
    'bg_card': '#1e293b',
    'text_white': '#ffffff',
    'text_gray': '#94a3b8',
    'accent_blue': '#3b82f6',
    'accent_gold': '#fbbf24',
}

def create_matplotlib_table():
    """Create schedule table using matplotlib"""
    fig, ax = plt.subplots(figsize=(12, 6), facecolor=COLORS['bg_dark'])
    ax.axis('off')
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 8)

    # Title
    ax.text(6, 7.5, "IMSA Michelin Pilot Challenge - Matplotlib Version",
           ha='center', fontsize=18, fontweight='bold', color=COLORS['text_white'])
    ax.text(6, 7, "Full Season Schedule",
           ha='center', fontsize=12, color=COLORS['text_gray'])

    # Headers
    header_y = 6.2
    table_left = 0.6
    table_width = 10.8

    header_bg = plt.Rectangle((table_left, header_y - 0.3), table_width, 0.5,
                             facecolor='#172033', edgecolor='#334155', linewidth=1, alpha=0.6)
    ax.add_patch(header_bg)

    ax.text(1.5, header_y, "Week", fontsize=13, color='#60a5fa', fontweight='bold', ha='center')
    ax.text(3.5, header_y, "Opens (UTC)", fontsize=13, color='#60a5fa', fontweight='bold', ha='center')
    ax.text(5.5, header_y, "Track", fontsize=13, color='#60a5fa', fontweight='bold', ha='left')

    # Rows
    y_pos = 5.4
    for idx, week in enumerate(sample_schedule):
        # Alternating backgrounds
        bg_color = '#1a2332' if idx % 2 == 0 else '#222d3f'
        row_bg = plt.Rectangle((table_left, y_pos - 0.35), table_width, 0.7,
                               facecolor=bg_color, edgecolor='#334155', linewidth=0.6, alpha=0.85)
        ax.add_patch(row_bg)

        ax.text(1.5, y_pos, str(week['week']), fontsize=12, color='#60a5fa',
               fontweight='bold', ha='center', va='center')
        ax.text(3.5, y_pos, week['date'], fontsize=11, color='#cbd5e1',
               ha='center', va='center')
        ax.text(5.5, y_pos, week['track'], fontsize=11, color=COLORS['text_white'],
               ha='left', va='center')

        y_pos -= 0.9

    # Footer
    ax.text(6, 0.5, "Generated by WompBot - Data from iRacing",
           ha='center', fontsize=9, color=COLORS['text_gray'], style='italic')

    buffer = BytesIO()
    plt.savefig(buffer, format='png', dpi=150, facecolor=COLORS['bg_dark'],
               bbox_inches='tight', pad_inches=0.3)
    plt.close()
    buffer.seek(0)

    with open('/tmp/matplotlib_table.png', 'wb') as f:
        f.write(buffer.getvalue())
    print("✓ Matplotlib table saved to /tmp/matplotlib_table.png")

def create_plotly_table():
    """Create schedule table using Plotly"""

    # Prepare data in columnar format
    weeks = [str(w['week']) for w in sample_schedule]
    dates = [w['date'] for w in sample_schedule]
    tracks = [w['track'] for w in sample_schedule]

    # Create row colors (alternating)
    row_colors = [COLORS['bg_card'] if i % 2 == 0 else '#222d3f' for i in range(len(sample_schedule))]

    fig = go.Figure()

    fig.add_trace(go.Table(
        header=dict(
            values=['<b>Week</b>', '<b>Opens (UTC)</b>', '<b>Track</b>'],
            fill_color='#172033',
            font=dict(color='#60a5fa', size=14, family='Inter, sans-serif'),
            align=['center', 'center', 'left'],
            height=40,
            line=dict(color='#334155', width=1)
        ),
        cells=dict(
            values=[weeks, dates, tracks],
            fill_color=[row_colors, row_colors, row_colors],
            font=dict(
                color=[['#60a5fa']*len(weeks), ['#cbd5e1']*len(dates), [COLORS['text_white']]*len(tracks)],
                size=12,
                family='Inter, sans-serif'
            ),
            align=['center', 'center', 'left'],
            height=35,
            line=dict(color='#334155', width=0.5)
        )
    ))

    fig.update_layout(
        title=dict(
            text=(
                "<b style='font-size:20px'>IMSA Michelin Pilot Challenge - Plotly Version</b><br>"
                "<span style='font-size:12px; color:#94a3b8'>Full Season Schedule</span>"
            ),
            font=dict(color=COLORS['text_white']),
            x=0.5,
            xanchor='center'
        ),
        paper_bgcolor=COLORS['bg_dark'],
        font=dict(family='Inter, sans-serif', color=COLORS['text_white']),
        width=1200,
        height=600,
        margin=dict(l=40, r=40, t=100, b=80)
    )

    # Add footer annotation
    fig.add_annotation(
        text='Generated by WompBot - Data from iRacing',
        xref='paper',
        yref='paper',
        x=0.5,
        y=-0.08,
        showarrow=False,
        font=dict(size=10, color=COLORS['text_gray'], family='Inter, sans-serif'),
        xanchor='center'
    )

    buffer = BytesIO()
    fig.write_image(buffer, format='png', engine='kaleido', scale=2)
    buffer.seek(0)

    with open('/tmp/plotly_table.png', 'wb') as f:
        f.write(buffer.getvalue())
    print("✓ Plotly table saved to /tmp/plotly_table.png")

if __name__ == '__main__':
    print("Creating comparison images...")
    create_matplotlib_table()
    create_plotly_table()
    print("\nComparison complete!")
    print("View the images:")
    print("  - Matplotlib: /tmp/matplotlib_table.png")
    print("  - Plotly:     /tmp/plotly_table.png")
